version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cleanarch_db
    environment:
      POSTGRES_DB: cleanarch_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: cleanarch_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: cleanarch_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "python -m src.infrastructure.database.migration_runner && python main.py"

volumes:
  postgres_data:

